- README.md
- manifest.yml
- nginx.conf
If `HMAC_SECRET` is found in the environment or in a user-provided service, HMAC-sign the request headers and pass the signature to the proxied application.
Flagging @dhcole @mbland and/or @ozzyjohnson for review, time permitting. Note: as suggested by @dhcole, this patch uses a fork of the staticfile buildpack that allows for custom nginx binaries--in this case, openresty.
> Sign proxied requests.

- manifest_base.yml
- manifest_dev.yml
- manifest_feature.yml
- manifest_prod.yml
- manifest_stage.yml
As per https://github.com/18F/fec-eregs/issues/89
Not all the apps are launched yet in cloud.gov, so some of these URLs might 404 or error.
> Add a route for eregs

- nginx.conf
Needed to add additional precaution to hide s3cmd attribute headers that could result in leaked bucket information.
> Please Review: added hide header for s3 transition bucket

- redirects-transition.conf
- redirects-www.conf
Changed FECIG redirect so that users are redirected to the transition site instead of being redirected to new site.
> Updated FECIG Redirect

- redirects-transition.conf
Removed redirect for record articles so that users can access articles on transition prior to 2004. Fixed broken redirect for reporting dates.
> Redirect fixes

- nginx.conf
- redirects-www.conf
Created regex redirects for all agenda pages. Also increased the upload limits for the client. This is necessary at times since we sometimes have large MP3 files.
This has been deployed to dev for testing and it seems to be working.
> Agenda page redirects and upload limits

- manifest_dev.yml
- manifest_prod.yml
- manifest_stage.yml
- nginx.conf
This change allows for s3 buckets to route through the `https://root_domain/files/` path. This includes legal documents as well as downloads:
**Example Legal Doc Path:**
https://fec-dev-proxy.app.cloud.gov/files/legal/aos/83238.pdf
**Example Downloads Path:**
https://fec-dev-proxy.app.cloud.gov/files/47a21f26da800501a1d66a9356251254673d1f0fcfb557f4ae589ea7.zip?Signature=TKjcEErMTfDLk5SgdsCGhAIAGrk%3D&Expires=1498507164&AWSAccessKeyId=AKIAKJRR72G36QMQSGNQ
> Added Legal and Download Bucket Routing

- nginx.conf
This permanently redirects the beta.fec.gov domain to www.fec.gov. Also added an x-frame-option same origin for the transition.fec.gov domain. This is needed so that iframes can be displayed on the transition domain.
> Redirect beta domain

- redirects-www.conf
Tested on my local NGINX Server by adding the redirect to nginx.conf:
> redirecting press release PDF URLs up to 1998

- redirects-transition.conf
- redirects-www.conf
Lines 53 through 57 of redirects-transition.conf have the BCRA redirects, let me know of they need to go in another location
> redirect BCRA pages

- redirects-www.conf
There were 2 AO URLs that were accidentally added during the web-app and cms merge. This redirects the bad URL to the correct one.
> Added redirects for incorrect AO urls

- redirects-transition.conf
- redirects-www.conf
Old forms page is retiring. URLs need to redirect to new page per this issue: https://github.com/18F/fec-cms/issues/1352
> Redirect FEC forms page

- redirects-transition.conf
Received request from information division to update links referenced in compliance map with the following updated links:
Coordination Periods should link to
https://www.fec.gov/help-candidates-and-committees/making-disbursements/coordinated-communications/
Federal Election Activity Periods should link to  (ONLY ON COMPLIANCE MAP). Need to make a separate change to the link on the compliance map for FEA
https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/definition-federal-election-activity-fea/
Electioneering Communication Periods should link to
https://www.fec.gov/help-candidates-and-committees/making-disbursements-ssf-or-connected-organization/making-electioneering-communications/
> Redirects for pages linked from compliance map

- nginx.conf
I would assume bulk data will take longer since those are the largest, I just tried this with https://fec-dev-proxy.app.cloud.gov/files/bulk-downloads/2016/indiv16.zip and it worked
> making the timeouts longer for the bulk s3 files

- nginx.conf
Addresses https://github.com/fecgov/fec-proxy/issues
Per our engineering sync on 2/16, this PR changes the `nginx` timeout to 60 seconds to match CMS timeout.
> Update keepalive_timeout to 60

- nginx.conf
- redirects-www.conf
Addresses https://github.com/fecgov/fec-proxy/issues/75
This will redirect anyone hitting https://www.fec.gov/files/bulk-downloads/ so that they hit the bucket directly instead of going through the proxy. This will allow the user to download large data sets without failure.
> Redirect bulk downloads bucket

- redirects-transition.conf
This redirects the toolkit page from transition to the new website.
Toolkit page is out of date and we are no longer using toolkits. H4CC includes latest info and forms
> Added toolkit redirect

- README.md
This changeset adds a bit of clarity to the README instructions around the proxy configuration.  It explicitly calls out the command given as an example for manual configuration and includes a note that the configuation is normaly set and configured in the manifest files for deployment.
> Improve README around configuration instructions

- redirects-transition.conf
Two compliance pages were put up for the PA/07 election. The first one has a misspelled URL (using two underscores intead of one) so we are redirecting that one to the correctly spelled URL.
Basically redirecting https://transition.fec.gov/info/ElectionDate/2018/PA__07.shtml to point to https://transition.fec.gov/info/ElectionDate/2018/PA_07.shtml
> Update redirects-transition.conf for misspelled URL

- redirects-transition.conf
This pull request creates redirects for the three FECfile manuals and the old yearly tips archive pages.
> Redirect links for tips pages and FECFile manuals on transition

- redirects-transition.conf
This updates the URLS for outdated brochures, pages and forms on transition, including:
Audio forms
AO brochure
Filing a Complaint brochure
Public funding brochure
Lobbying FAQ
Nonfederal fundraising FAQ
Corporate Guide
> Update redirects for info brochures and forms

- redirects-transition.conf
- redirects-www.conf
This will redirect old inspector general pages on transition to the new Wagtail page located here: https://www.fec.gov/office-inspector-general/. In addition any PDF documents that were stored under the /fecig/ directory on transition will be redirected to the wagtail documents bucket.
> Adds redirects for IG page and documents

- redirects-www.conf
This is for catching up on www redirects from old transition pages to their replacement pages in the CMS. The proxy redirects had already been done. 
This spreadsheet contains what we are redirecting in this PR:
https://docs.google.com/spreadsheets/d/1E8wnT98QYqWE3x3UK28mlgrxyDd3cghYFOuD2aKmxSQ/edit?usp=sharing
Resolves https://github.com/fecgov/fec-cms/issues/2350
> Catch up on content www redirects - cms issue 2350

- redirects-transition.conf
Redirects various quick answers and related pages on the transition site to their new homes on the main site. (See connected issue for list of pages being redirected/new pages.)
> Update transition redirects for quick answers

- redirects-transition.conf
Resolves #https://github.com/fecgov/fec-cms/issues/2593
The transition agenda pages 404s, this PR adds the agenda page redirects to transition.
> Adding redirects for agenda pages to transition

- redirects-www.conf
Merge after CMS PR: https://github.com/fecgov/fec-cms/pull/2581
This redirects the /advanced url to /browse-data
Related issue https://github.com/fecgov/fec-cms/issues/2306
> [Merge AFTER 7.7 release] Add redirect from /advanced to /browse-data

- redirects-transition.conf
Redirecting some outdated transition pages to new other filers pages and updating some existing redirects to point to the new pages.
Here are old and new URLs for testing:
> Update transition redirects to new other filers pages

- redirects-transition.conf
Updates for the lobbyist bundling redirects for 2019
> Update lobbyist bundling redirect

- redirects-www.conf
Updates were made to add redirects for all quick answers and to update redirects for the AF calculator and forms directory to the current pages.  See issue #2600.
> Update www redirects for quick answers and forms

- redirects-transition.conf
Deleted three specific form redirects for a broader redirect for the whole directory of forms, added redirect for AF calculator , and a quick answer page.
@patphongs for the broader redirects some did not have "redirect;" at the end, but most did, so we did that for our redirect we added "redirect;" . Just wanted to bring this to your attention.
> Update redirects for forms and AF

- nginx.conf
Increase timeout settings on the proxy in order to allow the API to retrieve longer queries.
> Increase timeout settings

- redirects-transition.conf
- redirects-www.conf
This fixes forms redirect go to Wagtail documents bucket instead: `/resources/cms-content/documents/`
> updated forms redirect to correct url

- redirects-transition.conf
Redirecting old inflation notices and related pages to FR notices in CMS. Redirected compliance map and sub directories to dates and deadlines page.
> Update redirects for inflation adjustment notices and compliance map

- redirects-www.conf
Redirecting old inflation notices and related pages to FR notices in CMS. Redirected compliance map and sub directories to dates and deadlines page.
@patphongs Please especially double check the broader redirect: we want everything in the "election date" sub directory to go to Dates and deadlines.
> Update www redirects 8.3 for inflation notices and compliance map

- manifest_dev.yml
- manifest_prod.yml
- manifest_stage.yml
Resolves #119 
Specifying `cflinuxfs3` stack to make sure that we are upgraded to the latest for testing before the cflinuxfs2 is deprecated in April.
I have tested pushing v3 in dev and stage with no issues.
> Added cflinuxfs3 to the stack specifications

- manifest_stage.yml
This adds the stage.fec.gov route after cdn configurations have been completed.
> Add stage.fec.gov route

- redirects-transition.conf
Updated some more publications and brochure links to remove them from transition to fec.gov
> 9.1 Redirect Work in transition

- redirects-transition.conf
Updating one redirect for old FECFile manual and adding three new ones for publications moving off transition.
How to test:
Here is a screenshot of the pages, the old URLs and the new URLs. Redirects for the special notices brochure and the  Guideline for Presentation in Good Order. An older FECFile manual was redirecting to the 2017 version, but that version was just replaced, so the redirect was updated to point to the new URL.
> Update transition redirects for 9.4

- redirects-transition.conf
The 2002 meeting minutes were in a subdirectory with a different name path than other years, so are 404'ing.
Old path: /agenda/agendas2002/*.pdf
I've put in a broader redirect for that subdirectory. 
If this works, it resolves #3266
> Adds redirect for the 2002 meeting minutes

- redirects-transition.conf
- redirects-www.conf
Points them to their transition pages.
Redirects to these pages
https://transition.fec.gov/finance/disclosure/2016MatchingFundSubmissions.shtml
https://transition.fec.gov/finance/2012matching/2012matching.shtml
https://transition.fec.gov/finance/2008matching/2008matching.shtml
https://transition.fec.gov/finance/disclosure/2004MatchingFundSubmissions.shtml
> Update redirects for presidential matching funds (transition)

- redirects-transition.conf
Removed transition domain's matching fund redirects and generic /finance/* and /finance/disclosure/* redirects as they were conflicting with www redirects
> Removed transition matching fund redirects that caused conflict

- redirects-transition.conf
- redirects-www.conf
This PR redirects the old transition open government page to the new wagtail page.
> Redirect old transition open government page to new wagtail page

- redirects-transition.conf
I forgot to add the domain to the transition redirect for the open government page. This PR adds this and corrects this error. This fix has already been deployed but needs to be backfilled into master.
> Adding domain to open government URL for transition redirect

- redirects-www.conf
These are the www redirects that would not work in Wagtail for ticket #3546 in Sprint 11.6
> www Redirects for ticket #3546

- redirects-www.conf
Contains the www redirects for guidance docs that were in E&J directory.
Also some updated:  A guidance doc file /em/respondent_guide.pdf already was in www redirect so I updated that one. Plus I noticed two older webinar addresses needed updating so I took care of those too and redirected to trainings page.
> Update guidance doc www redirects

- redirects-transition.conf
There were two broken transition links for the guidance documents. This PR should fix these links: 
https://transition.fec.gov/pdf/commissioners_tips.pdf
https://transition.fec.gov/law/policy/guidance/internal_controls_polcmtes_07.pdf
> Fix 2 broken transition links

- redirects-transition.conf
@djgarr submitted part 1 in https://github.com/fecgov/fec-proxy/pull/165
Puts transition redirects in for various RAD and Audit enforcement documents.
See our spreadsheet at https://docs.google.com/spreadsheets/d/1Jn5nC3fFku10RTCP5OAW6RiffjNBE4VwBubITQpCNK8/edit?usp=sharing
> Updates transition redirects for 12.3 part 2 of 2

- redirects-www.conf
@djgarr submitted part 1 already at https://github.com/fecgov/fec-proxy/pull/166
Adds www redirects for various RAD and Audit documents. Tested doing these as Wagtail redirects, but they didn't work (probably because of transition).
See [spreadsheet here](https://docs.google.com/spreadsheets/d/1Jn5nC3fFku10RTCP5OAW6RiffjNBE4VwBubITQpCNK8/edit#gid=195443225)
> Updates www redirects part 2 of 2 for 12.3

- redirects-www.conf
Resolves https://github.com/fecgov/fec-cms/issues/3451
This redirects /press/press[YEAR]/ to /press/news_releases/[year]/.
@dorothyyeager I have deployed these changes to dev so that you can easily test. These were the sample URLs to files that were broken. Now they should redirect correctly to the appropriate path on the content-s3 bucket. 
https://dev.fec.gov/press/press2008/20080226letter.PDF
https://dev.fec.gov/press/press2008/FECtoMcCain.PDF
https://dev.fec.gov/press/press2008/mccainletter.pdf
https://dev.fec.gov/press/press2008/20080220c1image.pdf
> Add redirect for press resource files

- redirects-transition.conf
Redirects for:
Administrative fines Resolves #3783 and mentioned in #3789
Election results #3827
Enforcement procedural materials page #3827
Question for @pat: Did I do the broader redirect correctly? Each of those directories in transition contains 1 or more documents but no subfolders.
> Updates transition redirects for various projects (admin fines, election results, enforcement page)

- redirects-transition.conf
Clean-up:
Updating old classic redirects to point to fec.gov
Eliminating duplicates
Adding bumpers and categories
Alphabetizing within categories.
Adds the following pubrec/ redirects:
Adds a redirect from /elecfil/passwords.html to https://webforms.fec.gov/psa/getstarted.htm
> WIP PR: Organizing transition redirects

- redirects-transition.conf
The redirects for 132. have been plugged in for the Enforcement Process, Embezzle, and Internet hearings.
>  Redirect comments on policy pages

- redirects-transition.conf
I missed the terminating semicolon during code review, @kathycarothers can you please backfill this in by merging this PR? Thanks!
> Fixed syntax for transition redirect

- redirects-transition.conf
Redirects for following pages were included:
FR notice: 
https://transition.fec.gov/law/policy/enforcement/notice_2008-13.pdf redirected to PDF uploaded at https://www.fec.gov/resources/cms-content/documents/notice_2008-13.pdf
Comment page at https://transition.fec.gov/law/policy/enforcement/2009/comments/comments.shtml redirected to https://www.fec.gov/legal-resources/policy/comments-received-notice-public-hearing-agency-procedures-and-policies-2009/
Numerous PDF files were included in broader redirect from /law/policy/enforcement/2009/comments/ to same file names at https://www.fec.gov/resources/cms-content/documents/ (See redirect spreadsheet for details.) Hoping I did this right!
Also took out some extra `"` that I noticed were in some broader IG page redirects.
Updated to add …
> Implements 2009 agency procedures page and hearing-related redirects

- redirects-transition.conf
Redirects /law/policy.shtml to new page at https://www.fec.gov/legal-resources/policy-other-guidance/.
(Also added a / to an entry I spotted missing it.)
> Adds redirect for Policy and other guidance page

- README.md
- manifest_dev.yml
- manifest_prod.yml
- manifest_stage.yml
Resolves #188
Resolves #140
- Specify to use `cf cli` version 7
- Reformat manifest files with newer format
- Reduce `dev` memory, increase `stage` and `prod` - max memory usage for `prod` for the past 6 months is ~170 but I set it to 512M to be extra cautious. Stage should match `prod` so I modified that value as well. 
- Specify `disk_quota` - default is `1G` and we only need `6.2M` - this doesn't impact performance, just how much space the app itself takes up.
- Implement rolling deployments, remove references to `autopilot` and `zero-downtime-push`
> Implement cf cli v7, rolling deployment

- .circleci/config.yml
- README.md
- bin/cf_deploy.sh
Resolves #164
Resolves #199
- Add CircleCI integration for proxy (borrowed heavily from pattern-library scripts)
- Deploy to appropriate space for each branch:
`develop` ➡️  `dev` space
`release*` ➡️ `stage` space
`master` ➡️ `prod` space
`feature` ➡️ no space
- Note: in order to add CircleCI integration, the **proxy needs to be added to our release/deploy and hotfix processes**. Redirects should be merged to the `develop` branch going forward.
At least two approvals, please
- Review `bash` syntax to make sure it makes sense/looks good
- Make a copy of this branch and name it `release/<your_branch_name>` and/or add `|| ${branch} == "<your_branch_name>" ]]` to this line: https://github.com/fecgov/fec-proxy/blob/ed7387c8ac1ee68bf42b02610c9b1fcb8560406a/bin/cf_deploy.sh#L14
So it reads:
``` …
```
> Add CircleCI integration for proxy

- redirects-www.conf
Updates broader www redirect for annual reports to https://www.fec.gov/resources/cms-content/documents/ar$1.pdf redirect;
Adds broader www redirect for annual reports from /resources/about-fec/reports/ar([0-9]+) to https://www.fec.gov/resources/cms-content/documents/ar$1.pdf redirect;
Adds www redirects for FOIA PDFs from /resources/foia/ to /resources/cms-content/documents/
Adds www redirects for agency report PDFs from /resources/about-fec/ to  /resources/cms-content/documents/
> Updates www redirects for PDFs made accessible

- README.md
- manifest_dev.yml
- manifest_prod.yml
- manifest_stage.yml
- nginx.conf
Resolves https://github.com/fecgov/fec-accounts/issues/316
- Update resolver to bosh and proxies to CMS `app.internal`
- Connect over `http` instead of `https` - per cloud.gov:
> Container to container networking uses an  overlay network used solely for this purpose. The Policy server is controlling access on this network. https for regular traffic is already terminated at the routers.
- Update deployment instructions to add network policy after deploy (shouldn't be required with rolling deployments but it's good to be safe)
List general components of the application that this PR will affect:
-  Routes - will allow proxy to connect to CMS on internal apps.internal route
- At least two reviewers, please
- Check out routes with `cf app cms` and see the two routes for the CMS, internal and …
> Connect to CMS using internal routes

- redirects-transition.conf
Updates broader transition redirect for annual reports to go from /about-fec/reports/ to /resources/cms-content/documents/
Adds redirects:
Old EEO page /eeo/policy_statement.shtml to https://www.fec.gov/about/equal-employment-opportunity/
Old EEO directory (broader)	/eeo/(.*).pdf to https://www.fec.gov/about/equal-employment-opportunity/
Old Records on Transition (broader) /pdf/record/(.*).pdf to https://www.fec.gov/resources/cms-content/documents/resources/record/$1.pdf
Older version of sale or use brochure /pages/brochures/sale_and_use_brochure.pdf to https://www.fec.gov/updates/sale-or-use-contributor-information/
Old Requests for legal consideration	/law/legalconsideration.shtml to https://www.fec.gov/legal-resources/policy-other-guidance/requests-legal-consideration/
> Adds or updates certain transition redirects (based on new develop)

- redirects-www.conf
Add redirects for litigation pages to the court case page: https://www.fec.gov/legal-resources/court-cases/
Add redirects for record articles within legal-resources pathed links to go to https://www.fec.gov/resources/record/$1.pdf
> Court case page related redirects

- manifest_dev.yml
- manifest_prod.yml
- manifest_stage.yml
Partial resolution to https://github.com/fecgov/fec-accounts/issues/317
- Route Proxy traffic through CDN routes only
- Merge after redirect PR: https://github.com/fecgov/fec-proxy-redirect/pull/4
- Note that we'll need to manually remove the routes after deployment due to the [additive-only](https://github.com/cloudfoundry/cloud_controller_ng/issues/1866) nature of deploying with manifests. Example: `cf unmap-route proxy app.cloud.gov --hostname fec-dev-proxy`
> Remove direct application routes

- redirects-transition.conf
Redirect campaign finance statistical summaries from the transition bucket to the content-s3 bucket.
> redirect transition campaign finance statistical summary files

- .circleci/config.yml
Resolves #210 - Remove unused `autopilot` plugin
Only one approval requested, thanks!
> Remove unused plugin

- bin/cf_deploy.sh
- manifest_dev.yml
- manifest_prod.yml
- manifest_stage.yml
Resolves https://github.com/fecgov/fec-accounts/issues/327
Part of https://github.com/fecgov/fec-accounts/issues/325
- Proxy connects to eregs with internal route, already uses bosh resolver
- add network policy to deploy script
- At least two reviewers, please
- Check out routes with `cf app eregs` and see the two routes for the eregs, internal and external
- Make a copy of this branch and name it and add `|| ${branch} == "<your_branch_name>" ]]` to this line: https://github.com/fecgov/fec-proxy/blob/ed7387c8ac1ee68bf42b02610c9b1fcb8560406a/bin/cf_deploy.sh#L14
So it reads:
```
if [[ ${branch} == "develop" || ${branch} == "<your_branch_name>" ]]; then
```
- Push up your branch
- Go to dev.fec.gov/regulations
- Make sure you can't access fec-dev-eregs.apps.internal
- Check that internal …
> Connect to eregs using internal route, add network policy to deploy script

- redirects-transition.conf
Resolves https://github.com/fecgov/fec-cms/issues/4217
Fix redirects for the first ten years report: https://www.fec.gov/resources/cms-content/documents/firsttenyears.pdf
Add redirects for EEO .shtml pages. See comment: https://github.com/fecgov/fec-cms/issues/4217#issuecomment-736803809
> Fix redirects related to EEO and first ten years report

- redirects-transition.conf
Resolves https://github.com/fecgov/fec-cms/issues/4201
Redirects have been added according to instructions here: https://github.com/fecgov/fec-cms/issues/4201#issuecomment-738217582 
BCRA redirects documented in this [spreadsheet](https://docs.google.com/spreadsheets/d/1Jn5nC3fFku10RTCP5OAW6RiffjNBE4VwBubITQpCNK8/edit#gid=2012864385) 🔒 
**Changes include:**
- Redirect for Interim reporting policy document migrated from https://transition.fec.gov/pages/bcra/fr67n230p71075_interim_reporting_policy.pdf and uploaded to https://www.fec.gov/resources/cms-content/documents/fr67n230p71075_interim_reporting_policy.pdf
- Redirects for old BCRA forms redirected to forms page
- Redirects for all other BCRA files within `https://transition.fec.gov/pages/bcra/` has been migrated to …
> BCRA file related redirects

- redirects-transition.conf
Redirects all of the alpha index pages to https://www.fec.gov/legal-resources/court-cases/court-case-alphabetical-index/
> Adds redirects for transition court case alpha index pages

- nginx.conf
Resolves #224 
Since `cache-control` is already handled at the application level in the CMS and Eregs, we do not need to control it in the proxy as well. This PR removes the additional `cache-control` header from the proxy.
> Remove cache-control header

- redirects-transition.conf
Reverses the order of the broader bcra webform redirects to fix the issue with them.
Resolves #4265
> Fixing order of broader bcra/ redirects

- redirects-transition.conf
Adding and organizing press statistical page redirects under proper bumper
Redirects for:
https://transition.fec.gov/press/bkgnd/history.shtml
https://transition.fec.gov/press/archived-campaign-finance-statistics.shtml
https://transition.fec.gov/press/campaign_finance_statistics-archive.shtml
Removes bumper for another statistics page (since it wasn't a subdirectory) and moves that redirect into press/ subdirectory.
> Adds transition redirects for press pages

- redirects-www.conf
- Adds redirects for some FOIA files (see redirect spreadsheet, accessibility tab) and https://github.com/fecgov/fec-cms/issues/4321
- Updates redirects that were pointing to the classic site or to retired transition pages (see redirect spreadsheet, PI 13 innovation tab). Ones for the classic site were updated to match what we are redirecting transition pages to.
- Organizes redirects alphabetically and adds bumpers for subdirectories
Note for @kathycarothers Please verify that the ones from the accessibility tab were added in correctly.
> Updates and organizes www redirects

- redirects-transition.conf
Redirects for 14.1. These are the em/enfpro/ links we need to remove from the Inventory list.
> Redirects for 14.1 Enforcement links

- redirects-transition.conf
Resolves #4447 by redirecting these three meeting pages:
/agenda/2010/agenda20100615.shtml to https://www.fec.gov/updates/june-16-2010-open-meeting/ 
/agenda/2012/agenda20120712.shtml to https://www.fec.gov/updates/july-12-2012-canceled-open-meeting/  
/agenda/2016/agenda20160128.shtml to https://www.fec.gov/updates/february-11-2016-open-meeting/
> Adds redirects for three open meeting pages

- redirects-transition.conf
I have added the redirects for contribution limits, efnprm, and elecmas.
> Redirects for 14.2 to move off transition

- redirects-transition.conf
Resolves #fec-cms/issues/4520
Redirects two FR notices from 2005 to equivalent in CMS
Redirects an old stray prior notice to dates and deadlines. We'll want to archive this notice with other old prior notices we've archived.
> Adds redirects for info/notices

- redirects-www.conf
Wagtail redirects did not work for three agenda pages, so adding in www. Also fixing typo spotted in the agenda section too.
> adds www redirect for three agenda pages

- manifest_dev.yml
- manifest_prod.yml
- manifest_stage.yml
Resolves https://github.com/fecgov/fec-cms/issues/4538
The larger case files for MURs can be as much as 650MB. When the proxy attempts to load those files, there is an error for "(28: No space left on device) while reading upstream". Since we are using the proxy to serve up those files back from the S3, additional disk space is required.
- Checkout this branch and perform a manual deploy to the dev environment 
- Attempt to view the once broken MUR file: https://dev.fec.gov/files/legal/murs/950.pdf and the file should now load, compared to production which is broken https://www.fec.gov/files/legal/murs/950.pdf
> Fix loading of large MUR PDF files

- redirects-transition.conf
We needed to fix the all public funds redirect to point to the XLS file rather than the PDF file.
> Fix all public funds transition redirect

- redirects-www.conf
Adds one www redirect for old brochure on transition and updates another. Both redirects point to https://www.fec.gov/help-candidates-and-committees/joint-fundraising-candidates-political-committees/.
> Updates www redirects for joint fundraising

- redirects-transition.conf
Updates two joint fundraising redirects to point to https://www.fec.gov/help-candidates-and-committees/joint-fundraising-candidates-political-committees/
> Updates joint fundraising redirects

- redirects-www.conf
Redirects https://www.fec.gov/resources/cms-content/documents/AllPublicFunds.pdf to https://www.fec.gov/resources/cms-content/documents/AllPublicFunds.xls
Resolves #[4616](https://github.com/fecgov/fec-cms/issues/4616)
> Adds redirect for Press Office PDF to XLS file

- redirects-transition.conf
Resolves https://github.com/fecgov/fec-cms/issues/4679
Create broader redirect for all litigation PDF files to go from transition to the new location on www
> redirect transition litigation documents to the new location on www

- redirects-transition.conf
Redirects RAD FAQ pages and documents linked on the RAD FAQ transition page.
Resolves [cms #4628](https://github.com/fecgov/fec-cms/issues/4628)
> Add redirects for RAD FAQ transition pages

- redirects-www.conf
Resolves https://github.com/fecgov/fec-cms/issues/4852
Resolves https://github.com/fecgov/fec-cms/issues/4808
Redirects two old E&Js that didn't have a working www redirect.
Redirects two PDFS replaced for accessibility reasons.
Fixed some alphabetizing issues.
See Innovation tab of the [Redirects spreadsheet](https://docs.google.com/spreadsheets/d/1vzN-wZlS8K8ZyfExSV3hwXDenDEN9KyyAUJFTI6OjKU/edit#gid=888923420)
> Adds www redirects (innovation)

- redirects-www.conf
As identified to fix the one wonky transition redirect from 16.2
/finance/disclosure/metadata/metadataforcandidatesummary.shtml should redirect to https://www.fec.gov/campaign-finance-data/candidate-summary-file-description/  (To make this work, we needed to fix this broader redirect in www).
> Fixes broader redirect for /finance

- redirects-transition.conf
Redirects old hearing files found in transition inventory meeting, updates foreign national brochure redirect and adds election page redirect.
See 16.6 tab and inventory tab (line 171) of redirects spreadsheet for details.
Question for @patphongs - can we redirect http://efilingapps.fec.gov/fecfiledoc/module_8_2_3.html via this repo? Or is that done elsewhere?
> Adds redirects for old hearing files

- redirects-e-regs.conf
Redirect partial of civil penalties regs.
How to test:
- Go to https://dev.fec.gov/regulations/111
- Navigate to the corresponding redirected sections: 111.24, 111.43, and 111.44
> [HOTFIX - MERGE WITH GITFLOW] Add partial redirect for civil penalties regulations

- redirects-transition.conf
Fixes three policy page redirects, adds a fourth and adds a redirect for an outdated Spanish brochure.
See 17.2 tab of [redirects spreadsheet](https://docs.google.com/spreadsheets/d/1vzN-wZlS8K8ZyfExSV3hwXDenDEN9KyyAUJFTI6OjKU/edit#gid=1065639266) for details.
Resolves #298
> Fixes policy page redirects

- redirects-transition.conf
Transition redirects for stray files in  law/policy and pages/ directories. See Transition Inventory, lines 165-461 for complete list.
To test: Check for syntax and for alphabetical order of redirects.
> Redirects 17.5 and 17.6

- redirects-www.conf
Some older forms and one annual report had names that didn't follow naming conventions or are being redirected to a court case page instead of a form, so broader redirects did not work. Wagtail redirect did not work either, so submitting this PR.
See lines 474 and 540-554 of the transition inventory spreadsheet.
> Adds www redirects for older forms

- redirects-transition.conf
One redirect was forgotten and the redirect URL was off by one letter for three others.
See lines 477, 551, 552 and 554 of the transition inventory spreadsheet
> Correcting 18.4 transition redirects after testing

- redirects-transition.conf
Needed to put an "o" into the URL to fix this redirect
> Fixing Form 9 instructions redirect

- redirects-www.conf
Unable to do via Wagtail due to broader redirect.
Redirects old form 3X instructions to current version
> Adds www redirects for old version of instructions

- redirects-e-regs.conf
New admin fines took effect on 12/29/2022. This PR adds the redirects for the three regulations that are affected to redirect their 2022 e-regs version to the eCFR.
> Adds redirects for 2022 admin fines

- redirects-e-regs.conf
Resolves #342 
Adds a partial redirect so that when navigating in the regulations app to each of these sections, it will display the correct fines information.
> Add partial redirects for admin fines

- redirects-transition.conf
The legislative history PDF redirects needed to go to their corresponding PDF files on the content s3. This PR corrects the resulting file.
> Fix legislative history PDF redirects

- redirects-transition.conf
Resolves #345 
Add redirects for archived prior notices on transition from 2018 and prior.
> Add redirects for archived prior notices reporting dates

- redirects-transition.conf
I needed to fix the failing dev build. I just realized that since I was trying to do a specific pattern match, it wouldn't allow the resulting redirect to the H4CC dates and deadlines page. Therefore, I needed to do a generic capture of the url and redirect all to H4CC dates and deadlines page. I tested and it built ok.
> Fix prior notice transition redirects

- redirects-www.conf
Updates some redirects from old transition pages to more current CMS pages (note www cleanup tab in [redirect spreadsheet](https://docs.google.com/spreadsheets/d/1vzN-wZlS8K8ZyfExSV3hwXDenDEN9KyyAUJFTI6OjKU/edit#gid=1171400168))
Corrects alphabetical order for some redirects
Takes off the https://www.fec.gov to convert the redirects into relative links (except in the broader ones).
Updates some broader redirects to point to a CMS landing page instead of transition pages.
> Updates and cleans up www redirects

- redirects-www.conf
Redirects /resources/cms-content/documents/FEC-2023-14-Request-for-Public-Comment-on-Report-Filing-and-Website-Usability.pdf to /resources/cms-content/documents/fedreg_notice_2023-14.pdf.
Needs to be a hotfix cc @AmyKort
> Hotfix: Redirects to official FR notice

- redirects-www.conf
Redirects /resources/cms-content/documents/FEC-2023-14-Request-for-Public-Comment-on-Report-Filing-and-Website-Usability.pdf to /resources/cms-content/documents/fedreg_notice_2023-14.pdf.
Needs to be a hotfix cc @AmyKort
> [MERGE WITH GITFLOW] Redirects to official FR notice

- redirects-www.conf
The filename for Form 9 instructions was changed from 
/fecform9i.pdf to /fecfrm9i.pdf
We are updating older www redirects and adding one from the old name to the new name for the guidance search.
> Update www redirects for Form 7 and for  Form 9 instructions

- redirects-www.conf
- Redirects www.fec.gov/pdf/fecfrm1 to its new URL at https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1.pdf
- Redirects `/members/former_members/...` to `/resources/about-fec/commissioners/....`
- Resolves [issue #5956](https://github.com/fecgov/fec-cms/issues/5956)
- Temporarily disable incorrect  redirect for non-existent `policy-guidance/documents`
- Fixes incorrect redirect for `national-party-committee-accounts`:
^/updates/fec-issues-interim-reporting-guidance-for-national-party-committee-accounts/ /updates/guidance-search/fec-issues-interim-reporting-guidance-for-national-party-committee-accounts/
**How to test:**
- This is deployed to dev
- You can test `fcfrm1` redirect here: https://dev.fec.gov/pdf/forms/fecfrm1.pdf
- You can test the `former_members` …
> Add www redirects for form 1 and former_members paths

- redirects-transition.conf
Updates redirects that pointed to the old URL for the election results page to now point to https://www.fec.gov/introduction-campaign-finance/election-results-and-voting-information/.
Updates redirects for guidance search documents to include /policy-guidance/ (if a PDF) in their URL. In a few cases, redirects needed to be added.
Full list of the updated and new redirects is in a separate tab of the [redirect spreadsheet](https://docs.google.com/spreadsheets/d/1vzN-wZlS8K8ZyfExSV3hwXDenDEN9KyyAUJFTI6OjKU/edit?usp=sharing) 
Note: Not all of the items on the redirect spreadsheet had a transition redirect to update. Only things that needed an update or a redirect are in this PR.
> Update redirects-transition.conf for new guidance search documents and election results page URLs

- redirects-e-regs.conf
Updates redirects per issues #391 and #392 
You can review the updated partials here (please ignore the funny Â characters, it's because we pull in the partials into the regulations site and it will be styled navigating to it there.):
- https://transition.fec.gov/regulations/page-ref-100-26.html
- https://transition.fec.gov/regulations/page-ref-111-24.html
- https://transition.fec.gov/regulations/page-ref-111-43.html
- https://transition.fec.gov/regulations/page-ref-111-44.html
> Update redirects-e-regs.conf for 2023

- manifest_dev.yml
- manifest_prod.yml
- nginx.conf
- redirects-eqs.conf
Will redirect for test-eqs.fec.gov and eqs.fec.gov domain. 
**Test redirect URLs:**
https://test-eqs.fec.gov/eqsdocsMUR/8017_15.pdf
https://test-eqs.fec.gov/eqsdocsADR/1152_07.pdf
https://test-eqs.fec.gov/eqsdocsAF/4632_01.pdf
https://test-eqs.fec.gov/eqs/searcheqs
https://test-eqs.fec.gov/
> [HOTFIX - MERGE WITH GITFLOW] Add test-eqs.fec.gov and eqs.fec.gov as a domain route and eqs redirects file v2

- redirects-www.conf
Need all COVID plans to redirect to /about/reports-about-fec/agency-operations/
> Update redirects-www.conf for COVID plan

- bin/cf_deploy.sh
- manifest_dev.yml
- manifest_prod.yml
- manifest_stage.yml
- nginx.conf
Removes the eregs app from proxy as it was shut down recently.
> remove eregs app from proxy

- redirects-www.conf
The `/efiling` redirect is overriding the redirects that we want to make using the CMS. Therefore, we are removing it from the proxy and handling that specific redirect using the CMS instead.
This has been deployed to stage for testing.
- Go to https://stage.fec.gov/efiling/ and it should redirect to https://stage.fec.gov/help-candidates-and-committees/filing-reports/electronic-filing/
- Go to https://stage.fec.gov/efiling/getting-started-fecfile-pilot/ and it should redirect to https://stage.fec.gov/help-candidates-and-committees/filing-reports/electronic-filing/getting-started-with-the-fecfile-pilot/
> [MERGE WITH GITFLOW - HOTFIX] Remove `/efiling` redirect

- redirects-www.conf
Replaces PR https://github.com/fecgov/fec-proxy/pull/417 in order to create as hotfix
Redirects the following removed EEO office documents to https://www.fec.gov/about/equal-employment-opportunity/
- /resources/cms-content/documents/2024-Federal-Election-Commission-EEO-Policy-Statement-Chairman-Cooksey.pdf
- /resources/cms-content/documents/No-FEAR-Notice-2024.pdf
- /resources/cms-content/documents/2023_No_FEAR_Act_Report.pdf
- /resources/cms-content/documents/2023-MD715-Report-May-2024.pdf
> [HOTFIX - MERGE WITH GITFLOW] EEO redirects

- .circleci/config.yml
- README.md
The Cloud.gov v2 API for Cloud Foundry is reaching its end-of-life. CF CLI versions 6 and 7 still rely on Cloud Foundry API v2 and will no longer work in coming months with foundations that have disabled it. However, CF CLI v8 no longer uses Cloud Foundry API v2. For more details, refer to this [link](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0032-cfapiv2-eol.md#impact-and-consequences).
1. circleci/config.yml, is upgraded to CF CLI v8.9.0. This version supports Cloud Foundry API v3. Deploying to a cloud.gov space should work smoothly with this update
1 developer
- install cf cli script
- deploy proxy (to cloud.gov space)
**Before:**
[cf cli v7.0.1 circleci build](https://app.circleci.com/pipelines/github/fecgov/fec-proxy/577/workflows/4065a32d-7eff-40cf-b0a9-ef9fb0f7 …
> upgrade cf cli
