manifest_base.yml
manifest_dev.yml
manifest_prod.yml

* Add separate environments for dev and production
* Limit nginx memory
cc @LindsayYoung

Add dev and production environments.

---

manifest_feature.yml

Deploy to the feature space with `cf target -s feature && cf push -f manifest_feature.yml`

Add manifest for feature space

---

manifest_prod.yml

prevents downtime when there are cf changes

add 2nd instance in production

---

nginx.conf

This is a fix for increasing upload size limits in Wagtail: https://github.com/18F/fec-cms/issues/906

Increased upload size limit

---

manifest_base.yml
manifest_dev.yml
manifest_feature.yml
manifest_prod.yml
manifest_stage.yml
nginx.conf

This works and is deployed on dev, We don't want to deploy to master until we are ready to make the switch.

[WIP] Feature/gov cloud

---

README.md
manifest_base.yml
nginx.conf

This will get us on version 1.11.13

Upgrades to the latest static file build pack

---

redirects-www.conf

Updated redirects for various pages.

Update additional redirects

---

manifest_prod.yml

adding the new route to the app

add www.fec.gov route

---

redirects-www.conf

Needed to fix incorrect redirect

Corrected redirect for help for candidates and committees page

---

redirects-www.conf

resolves https://github.com/18F/FEC/issues/4093 for archive MUR directory

added redirect for archive mur data

---

redirects-www.conf

I realized my PR worked but the previous fix was broad and before it so it was not coming through

reorder finance

---

nginx.conf

needed to turn off ipv6 to stop 500 errors

turned off ipv6

---

nginx.conf

Had to increase upload limit to account for larger audio file uploads

increased upload limit to 100 MB

---

redirects-www.conf

See issue: https://github.com/18F/openFEC-web-app/issues/2254

www redirects for 2254

---

manifest_dev.yml
manifest_prod.yml
manifest_stage.yml

This is waiting on the web app/cms merge

Proxy work for the merged cms-web app 

---

redirects-transition.conf
redirects-www.conf

fixed bad redirect encoding syntax

---

redirects-transition.conf

Nginx could not deploy due to rewrite syntax error. This PR fixes this error.

Fix rewrite syntax error

---

redirects-transition.conf

Redirecting https://transition.fec.gov/law/feca/feca.pdf to  https://www.fec.gov/resources/cms-content/documents/feca.pdf

Add redirect for the PDF of the statute

---

CONTRIBUTING.md
LICENSE.md
README.md

- Update project description - no longer in beta
-  Use FEC-wide license and contributing documents

 Use FEC-wide license and contributing documents

---

redirects-transition.conf

Implementing redirects for two outreach pages on transition plus catching up a few other older materials that need to be redirected to current pages. See spreadsheet at https://docs.google.com/spreadsheets/d/1oyzVuHY0Pl9M8kYREsXaNeClXBupOjmVFfFEa8QOnK4/edit#gid=1344463200

Update redirects for transition

---

redirects-www.conf

add pki redirect

---

redirects-www.conf

Redirecting www leg recs and annual reports

Update www for leg recs and annual reports

---

redirects-transition.conf

Updates transition redirects for legislative recommendations and annual reports
Resolves #2571

Updates transition redirects-legrecs

---

redirects-transition.conf

Resolves https://github.com/fecgov/fec-proxy/issues/107
Redirects audit hearing pages on transition site.

Added audit hearing redirects on transition site

---

redirects-www.conf

Adds new www redirects for old pages to new other filers pages. 
Specific for testing:

Update www redirects for other filers pages

---

redirects-www.conf

Updates to the www lobbyist bundling redirects 2019

Update www lobbyist redirects

---

blockips.conf

Unusually large activity from this IP

Block IP due to high activity

---

blockips.conf

Removed IP block as it was no longer needed

Removed ip block

---

redirects-transition.conf

Updated outreach and other redirects (EE0 etc.)

8.4 Redirects

---

redirects-www.conf

Updated www redirects for outreach and other pages (EEO etc.)

Update 8.4 www redirects

---

redirects-transition.conf

Redirects for E&J pages
@patphongs  see message below from original issue (#2776):
Work with @patphongs to fix three form redirects that are giving permissions error message (shown below).
/pdf/forms/fecfrm1ssf.pdf
/pdf/forms/fecfrm1nc.pdf
/pdf/forms/fecfrm1party.pdf
https://user-images.githubusercontent.com/24437369/55165670-3298a000-5144-11e9-9e67-8fd881511abf.png

Redirects for 8.5

---

redirects-transition.conf

Redirect old brochures and handouts

8.7 Redirects 

---

redirects-transition.conf

Adds redirect for presidential report uploaded to transition and then to CMS.

Update redirects to add one for a presidential report

---

redirects-transition.conf
redirects-www.conf

This updates the FECFile redirects in transition and also adds them to www.

Updated fecfile redirects

---

redirects-transition.conf

Redirect for the candidate registration brochure that has been updated to include presidential information.

9.5 Redirect Candidate Registration Brochure

---

redirects-transition.conf

Redirects for pages that are coming off of transition onto Wagtail.

Update redirects 10.2

---

manifest_dev.yml
manifest_prod.yml
manifest_stage.yml

Resolves #143 
Increase memory in all spaces to 128M
@patphongs if you approve, could you deploy off-hours?

Increase memory in all spaces to 128M

---

manifest_dev.yml
manifest_prod.yml
manifest_stage.yml

Increase proxy server memory to 256M.

---

redirects-www.conf

I have put in the redirects for www for 10.5 Non RAD pages.

Updated Redirects 10.5 Non RAD (www)

---

redirects-transition.conf

I have put in the redirects for the non RAD pages listed in the ticket.

Redirects 10.5 Non RAD pages

---

blockips.conf

Blocking IP due to abnormal activity

Block ip due to abnormal activity

---

redirects-transition.conf

Transition pages redirects for Sprint 11.6

---

redirects-transition.conf

Thank you @patphongs for helping to set these up. Sorry there wasn't more a easier pattern to follow!

Adds transition redirects for guidance doc PDFs

---

redirects-transition.conf

Need to add three redirects that were supposed to be in the last PR
/af/afcalc_20190101.shtml
/af/afcalc_20171228.shtml
/af/afcalc_20170101.shtml

Adds three missing redirects

---

redirects-transition.conf

Redirecting elecfil/, ej_compilation and some other PDFs to complete tasks in https://github.com/fecgov/fec-cms/issues/3883 and https://github.com/fecgov/fec-cms/issues/3894
How to test:
@kathycarothers  - please check 
- New redirects have the ^ rewrite before them and the redirect; after them
- New redirects are indexed correctly (in alphabetical/numerical order)
- If you want to doublecheck the links, they are on the content team redirect spreadsheet.
@patphongs - tagging you as reviewer as usual. 
Thank you for your help!

13.1 redirects 

---

redirects-transition.conf

@dorothyyeager There's some additional validation that I needed to do on the transition redirects. Please review and merge when you get the chance. Thanks!

Fixed invalid transition redirects

---

redirects-transition.conf

I have fixed the redirects that we had a problem in the first round.

Fixed redirects from 13.2

---

redirects-transition.conf

Redirects Enforcement statistics and things Dorothy found in inventory.
See https://github.com/fecgov/fec-cms/issues/4073

Adds redirects for tickets in 13.5

---

redirects-transition.conf

Please see Google redirect document

Updated 13.6 redirects on transition

---

.circleci/config.yml
README.md
bin/cf_deploy.sh
manifest_dev.yml
manifest_prod.yml
manifest_stage.yml
nginx.conf
redirects-transition.conf
redirects-www.conf

Release for Sprint 13.7. @fec-jli will deploy the release on Nov 24, 2020
@fec-jli please pair with @lbeaufort when doing the deploy, there's a couple of steps that need to be done in a certain order for this release.

[MERGE WITH GIT FLOW] Release/public 20201124

---

blockips.conf

Resolves #204 
Removed blocked IPs from the proxy

Remove blocked IPs

---

redirects-www.conf

Redirects for one court case name and legal resources

WWW redirects 13.9

---

redirects-transition.conf

Redirects for request of legal consideration, press, and accessibility

Update transition redirects 13.9

---

redirects-www.conf

Redirects previous ones to https://www.fec.gov/resources/cms-content/documents/status-of-fec-operations.pdf

[HOTFIX - MERGE WITH GITFLOW] Adds redirects for status doc

---

Staticfile
manifest_dev.yml
manifest_prod.yml
manifest_stage.yml
mime.types
nginx.conf

Resolves #200
- Move to nginx buildpack
- Remove embedded Ruby (`<% example %>`) from configuration file
- Move PROXIES to separate env vars (`CMS_PROXY` and `EREGS_PROXY`) to remove the need for imbedded Ruby
- Clean up inconsistent tabs and spaces
Resolves #212 
- Set DNS TTL to 1 second
**How to test**
- [Deploy manually](https://github.com/fecgov/fec-proxy#deployment) to dev space, make sure dev.fec.gov works

Move to Nginx buildpack

---

nginx.conf

Resolves https://github.com/fecgov/fec-proxy/issues/237
Removes extra chars from S3_LEGAL_AND_DOWNLOADS_URL variable to fix redirect

[HOTFIX - MERGE WITH GITFLOW] Fix S3_LEGAL_AND_DOWNLOADS_URL variable

---

redirects-transition.conf

See list at https://github.com/fecgov/fec-cms/issues/3936#issuecomment-778448738

Adds remaining pubrec redirects

---

redirects-transition.conf

Resolves #https://github.com/fecgov/fec-cms/issues/3059

Adds redirect for quarterly FOIA .zip files

---

redirects-transition.conf

Redirect for the library page on transition to go to www

Library on transition redirect

---

redirects-transition.conf

Addition of two redirects of Info pages.
Resolves https://github.com/fecgov/fec-cms/issues/4511

Adds redirects for Info

---

manifest_dev.yml
manifest_prod.yml
manifest_stage.yml
redirects-transition.conf
redirects-www.conf

This is for the sprint (14.4) release.
@patphongs  will deploy this.

[MERGE WITH GITFLOW] Release/public 20210427

---

redirects-transition.conf

Resolve https://github.com/fecgov/fec-cms/issues/4593

Matching funds redirects

---

redirects-transition.conf

Redirects old FR notice off transition to the version on Wagtail.

Adds redirect for 2009 FR notice on AO procedures

---

redirects-www.conf

Redirects matching fund zip files from 2008 and 2004.

Redirect matching fund zip files

---

redirects-e-regs.conf

Redirects
https://www.fec.gov/regulations/111-24/2021-annual-111
https://www.fec.gov/regulations/111-43/2021-annual-111
https://www.fec.gov/regulations/111-44/2021-annual-111
to 
their e-cfr pages

Add redirects for 2021 admin fines eregs

---

redirects-e-regs.conf
redirects-www.conf

This is the release for sprint 15.5. @pkfec will deploy the release on 8/24/21.

[MERGE WITH GIT FLOW] Release/public 20210824

---

redirects-www.conf

Updated 2 redirects for www

---

redirects-transition.conf

See lines 111 -136 in the [redirects spreadsheet, transition inventory tab](https://docs.google.com/spreadsheets/d/1vzN-wZlS8K8ZyfExSV3hwXDenDEN9KyyAUJFTI6OjKU/edit#gid=1787979934)

Adds redirects for stray files in /law

---

redirects-e-regs.conf
redirects-transition.conf
redirects-www.conf

 [MERGE WITH GITFLOW] Release/public 20211005

---

redirects-transition.conf

Redirects files in the 16.2 and transition inventory tabs of our [redirect spreadsheet](https://docs.google.com/spreadsheets/d/1vzN-wZlS8K8ZyfExSV3hwXDenDEN9KyyAUJFTI6OjKU/edit#gid=1787979934)
Fixes some alphabetical order issues.

16.2 redirects

---

redirects-transition.conf
redirects-www.conf

Sprint 16.2 release branch. @fec-jli will deploy the release on 11/02/2021

[MERGE WITH GITFLOW] Release/public 20211102

---

redirects-transition.conf

Redirects:
/law/media/Mullin_Winter_Tulsa_60.mp3 to https://www.fec.gov/resources/audio/2012/Mullin_Winter_Tulsa_60.mp3
/law/media/Socialists-Stream.mov to https://www.fec.gov/documents/3425/Socialists-Stream.mov
Resolves #https://github.com/fecgov/fec-cms/issues/4938

Adds two media file redirects

---

redirects-transition.conf
redirects-www.conf

Sprint 16.3 release branch. @patphongs will deploy the release on 11/16/2021.

[MERGE WITH GITFLOW] Release/public 20211116

---

redirects-transition.conf

Release of sprint 16.6 redirects

[MERGE WITH GITFLOW] Release/public 20220105

---

redirects-e-regs.conf
redirects-transition.conf

Sprint 17.2 release branch. @pkfec will deploy the release on 02/22/2022

[MERGE WITH GITFLOW] Release/public 20220222

---

redirects-transition.conf
redirects-www.conf

Sprint 17.3 release branch. @pkfec will deploy this release on Mar 8th.

[MERGE WITH GITFLOW] Release/public 20220308

---

redirects-transition.conf

Migrate or archive older files from old /open transition directory #5112

Migrate or archive older files

---

redirects-transition.conf
redirects-www.conf

This is for the sprint (17.5) release. @fec-jli will deploy this on 04/05/2022.

[MERGE WITH GITFLOW] Release/public 20220405

---

redirects-transition.conf

Resolves #308
This also resolves some nginx syntax errors that were accidentally pulled into the proxy repo.
**Redirects the following that are currently broken:**
- http://transition.fec.gov/audits/approve_auth_2006/roskam_for_congres.pdf
- http://transition.fec.gov/audits/approve_unauth_2006/americans_agnst_illgl_imm_pac.pdf
- http://transition.fec.gov/audits/approve_unauth_2006/comcast_corp_pac.pdf
- http://transition.fec.gov/audits/approve_auth_2006/tom_kean_for_senate.pdf
- http://transition.fec.gov/audits/approve_auth_2006/brady_for_congress.pdf
- http://transition.fec.gov/audits/approve_auth_2006/butterfield_for_congress.pdf
- http://transition.fec.gov/audits/approve_auth_2006/people_for_carl_andrews.pdf
- http://transition.fec.gov/audits/approve_auth_2006/talent_for_senate.pdf
- …

Fix audit report link redirects and other syntax fixes

---

redirects-transition.conf

4 redirects for 17 innovation
Resolves #https://github.com/fecgov/fec-cms/issues/5144

17 innovation redirects

---

redirects-transition.conf

This is the PR for the PI 17 innovation release. @lbeaufort  will deploy the release on 5/10

[MERGE WITH GIT FLOW] Release/public 20220510

---

redirects-transition.conf

Updated the redirects for lines 1120-1123

Partnership updates for redirects

---

redirects-www.conf

Updated redirects for lines 259-261 partnerships and then added Ie letter and nonconnected letter lines 347 and 348

Updated redirects

---

redirects-transition.conf

Updated Line 1218 to fix the url from "fecfrm" to "fecform"

updated line 1218

---

redirects-transition.conf

Redirects for transition for Press and RAD. I was only to get a couple in. I will have more to add

Transition redirects first part

---

redirects-www.conf

Needed to add a redirect for fecfrm9i_06.pdf in www

Redirect for fecfrm9i_06.pdf

---

redirects-transition.conf
redirects-www.conf

Sprint 19.1 release branch. @pkfec will deploy this release branch on 09/06/2022

[MERGE WITH GITFLOW] Release/public 20220906

---

redirects-transition.conf

A correction needed to be made to the redirect link for 3 redirects under rad/documents. It was incorrect.

Corrected the redirect link

---

redirects-www.conf

Add a new redirect for line 10 So this link for support would go to the data conversion tools link

Add a redirect for line 10

---

redirects-transition.conf
redirects-www.conf

Sprint 19.2 release branch. @pkfec will deploy this release on Sept 20th

[MERGE WITH GITFLOW] Release/public 20220920

---

redirects-e-regs.conf
redirects-www.conf

This is for 19.4 release. @cnlucas will deploy on 10/25

[MERGE WITH GITFLOW] Release/public 20221025

---

redirects-e-regs.conf
redirects-transition.conf
redirects-www.conf

This is for the sprint (20.2) release.
@fec-jli will deploy this 1/10

[MERGE WITH GITFLOW] Release/public 20230110

---

redirects-transition.conf

Resolves [fec-cms/issues/5515
](https://github.com/fecgov/fec-cms/issues/5515)
Redirects pages with /law/cfr/ej_conversion names to their new places on FEC.gov
[Redirect spreadsheet](https://docs.google.com/spreadsheets/d/1vzN-wZlS8K8ZyfExSV3hwXDenDEN9KyyAUJFTI6OjKU/edit#gid=1120792740), 20.4 tab, lines 9-17

Adds E&J appendix redirects

---

redirects-e-regs.conf
redirects-transition.conf

This is for the sprint (20.3) release.
@cnlucas will deploy this 1/24

[MERGE WITH GITFLOW] Release/public 20230124

---

redirects-transition.conf

This is for the sprint (20.4) release.
@cnlucas will deploy this 2/7

[MERGE WITH GITFLOW] Release/public 20230207

---

redirects-transition.conf
redirects-www.conf

Sprint 20.6 release branch. @pkfec will deploy release on Mar 7th

[MERGE ]Release/public 20230307

---

redirects-www.conf

Reverting the changes that were accidentally merged from [release/public-20230307](https://github.com/fecgov/fec-proxy/tree/revert-354-release/public-20230307)](https://github.com/fecgov/fec-proxy/pull/354)

Revert "[MERGE WITH GITFLOW ]Release/public 20230307"

---

README.md
redirects-www.conf

Release branch for Sprint 20.6. @pkfec will deploy the release on Mar 7th

[MERGE WITH GITFLOW]Release/public 20230307

---

redirects-www.conf

Re-adding www redirects that should have been deployed to prod on 3-7-2023, but got reverted somehow

[HOTFIX - MERGE WITH GITFLOW] Re-add www redirects that were reverted from the 3-7-2023 release

---

manifest_dev.yml
manifest_prod.yml
manifest_stage.yml

- Resolves #360 
This ticket upgrades the stack to cflinuxfs4. 
General components of the application that this PR will affect:
-  manifests 
- Deploy this branch to dev (will do on Monday)

upgrade stack to use cflinuxfs4

---

redirects-www.conf

Takes out extra space on line 302
Adds a / on line 427 after  ^

Fixing small things

---

redirects-www.conf

Revert "[MERGE WITH GITFLOW] Hotfix: Redirects to official FR notice"

---

redirects-www.conf

Line 420 has been fixed to add /resources/

Update redirects-www.conf - Need to fix a link for the Guidance Search

---

redirects-www.conf

Update the form boarder redirect path on line #564 to: https://www.fec.gov/resources/cms-content/documents/policy-guidance/$1
Related PR(s): https://github.com/fecgov/fec-proxy/pull/379

update form broader redirect path

---

redirects-transition.conf
redirects-www.conf

Sprint 23.3 release branch. @pkfec will deploy on Dec 5th, 2023
**Please approve this release branch only and do not click on merge pull request button.**

[MERGE WITH GITFLOW] Release/public 20231205

---

redirects-transition.conf
redirects-www.conf

Sprint 23.4 release branch. @cnlucas will deploy on Dec 18th, 2023

[MERGE WITH GITFLOW] Release/public 20231218

---

redirects-e-regs.conf
redirects-transition.conf

This is for the PI 23 innovation release.
@pkfec will deploy this

[MERGE WITH GITFLOW] Release/public 20240206

---

.circleci/config.yml
redirects-e-regs.conf

This is for the sprint PI 24.1 release.
@fec-jli will deploy this.

[MERGE WITH GITFLOW]Release/public 20240220
